### ISSUE TITLE
[solved] multiple card do not run on finetuning

### ISSUE THREAD

**Issue by HongyunQiu** [Lightning-AI/lit-llama#407] opened 2023-06-26 13:04 UTC
I am using a 8-A100-80G server to try the finetunes. I only changed the "device" in the finetune/lora.py file.  Single card training goes smoothly, I meet the problem when set to multiple card. It do not have any tranning progress here. It hangs after "Global seed set to xxxx" . 
I did try the lora, adapter and adapter_v2 and the results is similar. I also try the device =2 ,4, 8 and the results the same. Is there anything I am missing for the multiple card setup?  Thanks a lot !

Here is the output 

lit-llama/finetune/lora.py:216: JsonargparseDeprecationWarning: 
    Only use the public API as described in https://jsonargparse.readthedocs.io/en/stable/#api-reference.
    Importing from jsonargparse.cli is kept only to avoid breaking code that does not correctly use the public
    API. It will no longer be available from v5.0.0.

  from jsonargparse.cli import CLI
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
/home/ad/workspace/lit-llama/finetune/lora.py:216: JsonargparseDeprecationWarning: 
    Only use the public API as described in https://jsonargparse.readthedocs.io/en/stable/#api-reference.
    Importing from jsonargparse.cli is kept only to avoid breaking code that does not correctly use the public
    API. It will no longer be available from v5.0.0.

from jsonargparse.cli import CLI
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

[rank: 0] Global seed set to 1337
[rank: 1] Global seed set to 1338

And here is the GPU status

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB           Off| 00000000:4F:00.0 Off |                    0 |
| N/A   55C    P0               82W / 400W|  14305MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB           Off| 00000000:52:00.0 Off |                    0 |
| N/A   52C    P0               70W / 400W|  13843MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

**Comment by weilong-web** [comment] 2023-06-30 07:50
I just tried, it works well for me.
-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:0B:00.0 Off |                    0 |
| N/A   35C    P0    79W / 400W |  20906MiB / 81920MiB |     30%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:10:00.0 Off |                    0 |
| N/A   40C    P0   133W / 400W |  21040MiB / 81920MiB |     21%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:48:00.0 Off |                    0 |
| N/A   39C    P0    80W / 400W |  21028MiB / 81920MiB |     25%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:4E:00.0 Off |                    0 |
| N/A   35C    P0    88W / 400W |  21020MiB / 81920MiB |     23%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  On   | 00000000:9B:00.0 Off |                    0 |
| N/A   35C    P0   122W / 400W |  20986MiB / 81920MiB |     23%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  On   | 00000000:A1:00.0 Off |                    0 |
| N/A   40C    P0    99W / 400W |  21112MiB / 81920MiB |     35%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  On   | 00000000:DB:00.0 Off |                    0 |
| N/A   40C    P0   117W / 400W |  20798MiB / 81920MiB |     24%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:E0:00.0 Off |                    0 |
| N/A   35C    P0   107W / 400W |  21014MiB / 81920MiB |     36%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1678562      C                                   20904MiB |
|    1   N/A  N/A   1678706      C                                   21038MiB |
|    2   N/A  N/A   1678707      C                                   21026MiB |
|    3   N/A  N/A   1678708      C                                   21028MiB |
|    4   N/A  N/A   1678709      C                                   20984MiB |
|    5   N/A  N/A   1678710      C                                   21110MiB |
|    6   N/A  N/A   1678711      C                                   20796MiB |
|    7   N/A  N/A   1678712      C                                   21012MiB |
+-----------------------------------------------------------------------------+

**Comment by HongyunQiu** [comment] 2023-07-08 08:46
I have solved this problem. It is a BIOS setting of the server.
Need to set the ACS to disable.

Thanks to everyone here.

**Comment by aniketmaurya** [comment] 2023-08-08 19:02
closing since the issue is solved by the author

**Closed by aniketmaurya** 2023-08-08 19:02 UTC
