### ISSUE TITLE
Command python generate.py --quantize true --prompt "Hello, my name is" Not working

### ISSUE THREAD

**Issue by rajeevbaalwan** [Lightning-AI/lit-llama#70] opened 2023-03-31 10:49 UTC
Getting below error while executing the given command.

```
Loading model ...
Traceback (most recent call last):
  File "generate.py", line 147, in <module>
    CLI(main)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "generate.py", line 110, in main
    model.load_state_dict(checkpoint)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2027, in load_state_dict
    load(self, state_dict)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2009, in load
    module._load_from_state_dict(
  File "/mnt/hdd1/rajeevy/nlp/Lama/lit-llama/lit_llama/quantization.py", line 35, in _load_from_state_dict
    weight_key = next(name for name in local_state_dict.keys() if name.endswith("weight"))
StopIteration```

**Comment by awaelchli** [comment] 2023-03-31 10:55
What checkpoint are you using here? Did you follow the steps in the README to obtain the pretrained weights (and convert them)?

**Comment by rajeevbaalwan** [comment] 2023-03-31 10:58
I obtained checkpoints from hugging face after filling out the google form.

**Comment by lantiga** [comment] 2023-03-31 11:00
I believe the checkpoints from HF are different from the ones distributed by meta.
We can probably write an import function from those as well. I'm wondering how Meta hasn't shut down that HF repo though, as it violates their ToS :-)

**Comment by rajeevbaalwan** [comment] 2023-03-31 11:02
That might be down now. I obtained the checkpoints weeks back. Please provide the required function to support HF checkpoints as this might be helpful for a lot of folks who got checkpoints from HF.

**Comment by carmocca** [comment] 2023-03-31 11:51
Duplicate of #64

We might want to add a check that something was loaded to avoid the ugly StopIteration too

**Comment by lantiga** [comment] 2023-03-31 12:09
Agreed @carmocca let's do it

**Comment by awaelchli** [comment] 2023-04-04 11:27
@rajeevbaalwan You can run `scripts/convert_hf_checkpoint.py` now on the HF checkpoint file thanks to #90

**Comment by rajeevbaalwan** [comment] 2023-04-05 10:49
@awaelchli I have executed the script and getting below error.
```
Traceback (most recent call last):
  File "scripts/convert_hf_checkpoint.py", line 6, in <module>
    from lit_llama.model import LLaMA, LLaMAConfig
ModuleNotFoundError: No module named 'lit_llama'
```

**Comment by lantiga** [comment] 2023-04-05 16:49
Interesting. Can you `pip install -e .` prior to running the command?

**Comment by rajeevbaalwan** [comment] 2023-04-05 19:20
> pip install -e .

Now I'm getting below error 
```
python scripts/convert_hf_checkpoint.py --hf_checkpoint_path checkpoints/lit-llama/7B
Loading weights from pretrained LLaMA 7B
Traceback (most recent call last):
  File "scripts/convert_hf_checkpoint.py", line 96, in <module>
    CLI(convert_hf_checkpoint)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "scripts/convert_hf_checkpoint.py", line 25, in convert_hf_checkpoint
    model_hf = LlamaForCausalLM.from_pretrained(hf_checkpoint_path)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2250, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/transformers/configuration_utils.py", line 546, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: checkpoints/lit-llama/7B does not appear to have a file named config.json. Checkout 'https://huggingface.co/checkpoints/lit-llama/7B/None' for available files.
```

Looks like it need some specific files,I have below files in HF checkpoints.
```
checklist.chk   consolidated.00.pth  llama-7b.bin  params.json 
```

**Comment by lantiga** [comment] 2023-04-06 10:28
This is an issue with HF transformers (we use that to load the model) not finding the info it needs to load.

I did 
```
git clone https://huggingface.co/decapoda-research/llama-7b-hf
```

which gave me

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/191033/230351169-8cf817c9-0ef5-4ae6-a4ee-7cb1e6e0d3cc.png">

**Comment by rajeevbaalwan** [comment] 2023-04-07 06:41
@lantiga I have used the clone you mentioned.
```
git clone https://huggingface.co/decapoda-research/llama-7b-hf
```
and then used below command pointing it to actual HF checkpoints which I have:
```
python scripts/convert_hf_checkpoint.py --hf_checkpoint_path ../pretrained_model/llama_7b/7B
```
This give me below files in checkpoint folder:
```
ls checkpoints/
lit-llama.ckpt
```
There is no tokenizer.model saved in checkpoints directory. So I used tokenizer available with HF checkpoints and executed the command as mentioned in ReadMe.
```
CUDA_VISIBLE_DEVICES=1 python generate.py  --prompt "Here's what people think about pineapple and pizza: " --checkpoint_path checkpoints/lit-llama.ckpt  --tokenizer_path checkpoints/lit-llama/tokenizer.model  --quantize true
Loading model ...
Time to load model: 22.09 seconds.
Global seed set to 1234
Here's what people think about pineapple and pizza:  Threerx dictionary Filtervd marg functionalargcx disturbPixel merged orn likelyヒ constructстр erste onClick converting indirect fundInflzhearchstraße df sollte seinesciteskich Nation jednakided BashServer celuilimit drumsNSStringΥ homme가 TrumpgDisŻccióшения Petersburg


Time for inference: 6.85 sec total, 7.30 tokens/sec
Memory used: 9.27 GB
```

As you can see this not even close to what ReadMe shows. Am i missing something here ?

**Comment by rajeevbaalwan** [comment] 2023-04-07 06:49
> This is an issue with HF transformers (we use that to load the model) not finding the info it needs to load.
> 
> I did
> 
> ```
> git clone https://huggingface.co/decapoda-research/llama-7b-hf
> ```
> 
> which gave me
> 
> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/191033/230351169-8cf817c9-0ef5-4ae6-a4ee-7cb1e6e0d3cc.png">

I think there is some issue in HF checkpoint conversion, I'm getting below output.
```
python scripts/convert_hf_checkpoint.py --hf_checkpoint_path ../pretrained_model/llama_7b/7B
Loading weights from pretrained LLaMA 7B
Some weights of the model checkpoint at ../pretrained_model/llama_7b/7B were not used when initializing LlamaForCausalLM: ['encoder.transformer.23.layer_norm_1.weight', 'encoder.transformer.19.feed_forward.linear_2.weight', 'encoder.transformer.6.feed_forward.linear_1.weight', 'encoder.transformer.22.self_attn.final_linear.weight', 'encoder.transformer.10.self_attn.linear_layers.0.weight', 'encoder.transformer.17.self_attn.linear_layers.0.weight', 'encoder.transformer.15.feed_forward.linear_2.weight', 'encoder.transformer.22.layer_norm_2.weight', 'encoder.transformer.3.self_attn.linear_layers.0.weight', 'encoder.transformer.31.self_attn.linear_layers.2.weight', 'encoder.transformer.18.feed_forward.linear_2.weight', 'encoder.transformer.27.layer_norm_1.weight', 'encoder.transformer.12.layer_norm_1.weight', 'encoder.transformer.21.self_attn.final_linear.weight', 'encoder.transformer.25.feed_forward.linear_1.weight', 'encoder.transformer.4.self_attn.linear_layers.2.weight', 'encoder.transformer.6.layer_norm_1.weight', 'encoder.transformer.8.self_attn.linear_layers.1.weight', 'encoder.transformer.20.feed_forward.linear_2.weight', 'encoder.transformer.1.self_attn.linear_layers.1.weight', 'encoder.transformer.8.self_attn.linear_layers.0.weight', 'encoder.transformer.19.feed_forward.linear_1.weight', 'encoder.transformer.21.layer_norm_1.weight', 'encoder.transformer.4.layer_norm_1.weight', 'encoder.transformer.16.feed_forward.linear_1.weight', 'encoder.transformer.8.feed_forward.linear_2.weight', 'encoder.transformer.18.self_attn.linear_layers.2.weight', 'encoder.transformer.20.layer_norm_1.weight', 'encoder.transformer.1.self_attn.final_linear.weight', 'encoder.transformer.11.layer_norm_2.weight', 'encoder.transformer.12.layer_norm_2.weight', 'encoder.transformer.1.feed_forward.linear_2.weight', 'encoder.transformer.10.self_attn.linear_layers.2.weight', 'encoder.transformer.15.self_attn.final_linear.weight', 'encoder.transformer.20.self_attn.final_linear.weight', 'encoder.transformer.13.feed_forward.linear_gate.weight', 'encoder.transformer.12.feed_forward.linear_1.weight', 'encoder.transformer.28.self_attn.linear_layers.0.weight', 'encoder.transformer.30.self_attn.final_linear.weight', 'encoder.transformer.22.feed_forward.linear_gate.weight', 'encoder.transformer.29.feed_forward.linear_2.weight', 'encoder.transformer.6.self_attn.linear_layers.1.weight', 'encoder.transformer.25.self_attn.linear_layers.2.weight', 'encoder.transformer.13.layer_norm_2.weight', 'encoder.transformer.9.feed_forward.linear_1.weight', 'encoder.transformer.22.self_attn.linear_layers.1.weight', 'encoder.transformer.0.feed_forward.linear_1.weight', 'encoder.transformer.14.self_attn.final_linear.weight', 'encoder.transformer.8.feed_forward.linear_1.weight', 'encoder.transformer.9.self_attn.linear_layers.2.weight', 'encoder.transformer.21.feed_forward.linear_2.weight', 'encoder.transformer.28.self_attn.linear_layers.2.weight', 'encoder.transformer.6.layer_norm_2.weight', 'encoder.transformer.27.self_attn.linear_layers.1.weight', 'encoder.transformer.4.self_attn.final_linear.weight', 'encoder.transformer.3.self_attn.linear_layers.1.weight', 'encoder.transformer.2.feed_forward.linear_2.weight', 'encoder.transformer.16.feed_forward.linear_gate.weight', 'encoder.transformer.18.feed_forward.linear_1.weight', 'encoder.transformer.21.feed_forward.linear_1.weight', 'encoder.transformer.7.feed_forward.linear_gate.weight', 'encoder.transformer.23.self_attn.linear_layers.0.weight', 'encoder.transformer.8.self_attn.linear_layers.2.weight', 'encoder.transformer.23.feed_forward.linear_1.weight', 'encoder.transformer.14.self_attn.linear_layers.1.weight', 'encoder.transformer.31.feed_forward.linear_1.weight', 'embedding.word.embedding.weight', 'encoder.transformer.8.layer_norm_1.weight', 'encoder.transformer.12.self_attn.linear_layers.1.weight', 'encoder.transformer.24.layer_norm_2.weight', 'encoder.transformer.5.feed_forward.linear_2.weight', 'encoder.transformer.29.layer_norm_1.weight', 'encoder.transformer.13.feed_forward.linear_2.weight', 'encoder.transformer.11.self_attn.linear_layers.2.weight', 'encoder.transformer.26.feed_forward.linear_2.weight', 'encoder.transformer.1.feed_forward.linear_gate.weight', 'encoder.transformer.20.feed_forward.linear_1.weight', 'encoder.transformer.29.self_attn.final_linear.weight', 'encoder.transformer.31.layer_norm_1.weight', 'encoder.transformer.7.self_attn.linear_layers.2.weight', 'encoder.transformer.13.self_attn.linear_layers.2.weight', 'encoder.transformer.18.self_attn.linear_layers.1.weight', 'encoder.transformer.29.self_attn.linear_layers.2.weight', 'encoder.transformer.7.layer_norm_1.weight', 'encoder.transformer.16.self_attn.linear_layers.2.weight', 'encoder.transformer.9.layer_norm_1.weight', 'encoder.transformer.13.self_attn.linear_layers.1.weight', 'encoder.transformer.9.self_attn.final_linear.weight', 'encoder.transformer.20.self_attn.linear_layers.0.weight', 'encoder.transformer.23.feed_forward.linear_2.weight', 'encoder.transformer.31.feed_forward.linear_2.weight', 'encoder.transformer.6.self_attn.final_linear.weight', 'encoder.transformer.16.layer_norm_1.weight', 'encoder.transformer.21.self_attn.linear_layers.0.weight', 'encoder.transformer.16.self_attn.final_linear.weight', 'encoder.transformer.27.feed_forward.linear_gate.weight', 'encoder.transformer.26.self_attn.linear_layers.0.weight', 'encoder.transformer.26.self_attn.final_linear.weight', 'encoder.transformer.29.self_attn.linear_layers.1.weight', 'encoder.transformer.9.layer_norm_2.weight', 'encoder.transformer.14.layer_norm_1.weight', 'encoder.transformer.23.layer_norm_2.weight', 'encoder.transformer.15.self_attn.linear_layers.2.weight', 'encoder.transformer.2.self_attn.linear_layers.0.weight', 'encoder.transformer.13.feed_forward.linear_1.weight', 'encoder.transformer.30.feed_forward.linear_gate.weight', 'encoder.transformer.11.layer_norm_1.weight', 'encoder.transformer.12.self_attn.linear_layers.2.weight', 'encoder.transformer.20.feed_forward.linear_gate.weight', 'encoder.transformer.12.feed_forward.linear_gate.weight', 'encoder.transformer.19.layer_norm_1.weight', 'encoder.transformer.8.layer_norm_2.weight', 'encoder.transformer.26.self_attn.linear_layers.2.weight', 'encoder.transformer.26.layer_norm_2.weight', 'encoder.transformer.13.self_attn.final_linear.weight', 'encoder.transformer.3.layer_norm_1.weight', 'encoder.transformer.22.feed_forward.linear_2.weight', 'encoder.transformer.10.feed_forward.linear_1.weight', 'encoder.transformer.26.feed_forward.linear_gate.weight', 'encoder.transformer.15.self_attn.linear_layers.1.weight', 'encoder.transformer.1.self_attn.linear_layers.2.weight', 'encoder.transformer.21.self_attn.linear_layers.1.weight', 'encoder.transformer.26.self_attn.linear_layers.1.weight', 'encoder.transformer.23.self_attn.linear_layers.1.weight', 'encoder.transformer.0.self_attn.linear_layers.2.weight', 'encoder.transformer.28.self_attn.linear_layers.1.weight', 'encoder.transformer.16.self_attn.linear_layers.0.weight', 'encoder.transformer.23.feed_forward.linear_gate.weight', 'encoder.transformer.22.self_attn.linear_layers.2.weight', 'encoder.transformer.7.layer_norm_2.weight', 'encoder.transformer.27.layer_norm_2.weight', 'encoder.transformer.28.layer_norm_2.weight', 'encoder.transformer.30.feed_forward.linear_2.weight', 'encoder.transformer.28.self_attn.final_linear.weight', 'encoder.transformer.11.feed_forward.linear_gate.weight', 'encoder.transformer.24.self_attn.final_linear.weight', 'encoder.transformer.28.feed_forward.linear_gate.weight', 'encoder.transformer.15.feed_forward.linear_gate.weight', 'encoder.transformer.5.self_attn.linear_layers.2.weight', 'encoder.transformer.18.feed_forward.linear_gate.weight', 'encoder.transformer.19.feed_forward.linear_gate.weight', 'encoder.transformer.21.feed_forward.linear_gate.weight', 'encoder.transformer.5.feed_forward.linear_1.weight', 'encoder.transformer.2.self_attn.linear_layers.2.weight', 'encoder.transformer.7.feed_forward.linear_2.weight', 'encoder.transformer.0.feed_forward.linear_gate.weight', 'encoder.transformer.3.feed_forward.linear_2.weight', 'encoder.transformer.19.layer_norm_2.weight', 'encoder.transformer.14.feed_forward.linear_gate.weight', 'encoder.transformer.11.self_attn.linear_layers.0.weight', 'encoder.transformer.1.self_attn.linear_layers.0.weight', 'encoder.transformer.24.feed_forward.linear_gate.weight', 'encoder.transformer.28.feed_forward.linear_1.weight', 'encoder.transformer.7.feed_forward.linear_1.weight', 'encoder.transformer.5.layer_norm_1.weight', 'encoder.transformer.17.feed_forward.linear_2.weight', 'encoder.transformer.15.self_attn.linear_layers.0.weight', 'encoder.transformer.17.feed_forward.linear_gate.weight', 'encoder.transformer.11.feed_forward.linear_1.weight', 'encoder.transformer.25.self_attn.linear_layers.0.weight', 'encoder.transformer.3.self_attn.linear_layers.2.weight', 'encoder.transformer.19.self_attn.linear_layers.0.weight', 'encoder.transformer.0.feed_forward.linear_2.weight', 'encoder.transformer.2.self_attn.linear_layers.1.weight', 'encoder.transformer.15.layer_norm_2.weight', 'encoder.transformer.9.feed_forward.linear_2.weight', 'encoder.transformer.15.feed_forward.linear_1.weight', 'encoder.transformer.4.layer_norm_2.weight', 'encoder.transformer.17.self_attn.final_linear.weight', 'encoder.transformer.30.self_attn.linear_layers.2.weight', 'encoder.transformer.9.self_attn.linear_layers.0.weight', 'encoder.transformer.11.self_attn.linear_layers.1.weight', 'encoder.transformer.13.layer_norm_1.weight', 'encoder.transformer.4.self_attn.linear_layers.1.weight', 'encoder.transformer.4.self_attn.linear_layers.0.weight', 'encoder.transformer.17.self_attn.linear_layers.1.weight', 'encoder.transformer.20.self_attn.linear_layers.2.weight', 'encoder.transformer.25.layer_norm_2.weight', 'encoder.transformer.5.self_attn.linear_layers.1.weight', 'encoder.transformer.19.self_attn.final_linear.weight', 'encoder.transformer.10.feed_forward.linear_gate.weight', 'encoder.transformer.26.feed_forward.linear_1.weight', 'encoder.transformer.3.feed_forward.linear_gate.weight', 'encoder.transformer.24.self_attn.linear_layers.2.weight', 'encoder.transformer.2.layer_norm_2.weight', 'encoder.transformer.18.layer_norm_2.weight', 'encoder.transformer.29.feed_forward.linear_1.weight', 'encoder.transformer.24.self_attn.linear_layers.0.weight', 'encoder.transformer.28.feed_forward.linear_2.weight', 'encoder.transformer.29.feed_forward.linear_gate.weight', 'encoder.transformer.8.self_attn.final_linear.weight', 'encoder.transformer.10.feed_forward.linear_2.weight', 'encoder.transformer.30.layer_norm_2.weight', 'encoder.transformer.10.layer_norm_1.weight', 'encoder.transformer.28.layer_norm_1.weight', 'encoder.transformer.14.self_attn.linear_layers.0.weight', 'encoder.transformer.0.layer_norm_1.weight', 'encoder.transformer.25.layer_norm_1.weight', 'encoder.transformer.31.self_attn.final_linear.weight', 'encoder.transformer.18.self_attn.linear_layers.0.weight', 'encoder.transformer.2.feed_forward.linear_1.weight', 'encoder.transformer.18.self_attn.final_linear.weight', 'encoder.transformer.5.layer_norm_2.weight', 'encoder.transformer.1.layer_norm_2.weight', 'encoder.transformer.29.self_attn.linear_layers.0.weight', 'encoder.transformer.4.feed_forward.linear_1.weight', 'encoder.transformer.12.self_attn.linear_layers.0.weight', 'encoder.transformer.30.self_attn.linear_layers.1.weight', 'encoder.transformer.31.self_attn.linear_layers.0.weight', 'target.lm.output_layer.weight', 'encoder.transformer.22.feed_forward.linear_1.weight', 'encoder.transformer.7.self_attn.final_linear.weight', 'encoder.transformer.10.self_attn.final_linear.weight', 'encoder.transformer.19.self_attn.linear_layers.1.weight', 'encoder.transformer.25.feed_forward.linear_2.weight', 'encoder.transformer.5.feed_forward.linear_gate.weight', 'encoder.transformer.3.self_attn.final_linear.weight', 'encoder.transformer.9.feed_forward.linear_gate.weight', 'encoder.transformer.19.self_attn.linear_layers.2.weight', 'encoder.transformer.27.self_attn.linear_layers.2.weight', 'encoder.transformer.27.self_attn.final_linear.weight', 'encoder.transformer.29.layer_norm_2.weight', 'encoder.transformer.3.layer_norm_2.weight', 'encoder.transformer.0.self_attn.final_linear.weight', 'encoder.transformer.3.feed_forward.linear_1.weight', 'encoder.transformer.0.self_attn.linear_layers.1.weight', 'encoder.transformer.20.self_attn.linear_layers.1.weight', 'encoder.transformer.24.feed_forward.linear_2.weight', 'encoder.transformer.17.feed_forward.linear_1.weight', 'encoder.transformer.6.self_attn.linear_layers.0.weight', 'encoder.transformer.26.layer_norm_1.weight', 'encoder.transformer.6.feed_forward.linear_2.weight', 'encoder.transformer.2.self_attn.final_linear.weight', 'encoder.transformer.18.layer_norm_1.weight', 'encoder.transformer.6.self_attn.linear_layers.2.weight', 'encoder.transformer.31.layer_norm_2.weight', 'encoder.transformer.21.self_attn.linear_layers.2.weight', 'encoder.transformer.7.self_attn.linear_layers.1.weight', 'encoder.transformer.12.feed_forward.linear_2.weight', 'encoder.transformer.24.self_attn.linear_layers.1.weight', 'encoder.transformer.23.self_attn.final_linear.weight', 'encoder.transformer.24.layer_norm_1.weight', 'encoder.transformer.25.self_attn.linear_layers.1.weight', 'encoder.transformer.5.self_attn.linear_layers.0.weight', 'encoder.transformer.10.layer_norm_2.weight', 'encoder.transformer.30.self_attn.linear_layers.0.weight', 'encoder.transformer.17.layer_norm_2.weight', 'encoder.transformer.16.self_attn.linear_layers.1.weight', 'encoder.transformer.1.layer_norm_1.weight', 'encoder.transformer.27.feed_forward.linear_2.weight', 'encoder.transformer.6.feed_forward.linear_gate.weight', 'encoder.transformer.2.layer_norm_1.weight', 'encoder.transformer.22.layer_norm_1.weight', 'encoder.transformer.4.feed_forward.linear_gate.weight', 'encoder.transformer.11.feed_forward.linear_2.weight', 'encoder.transformer.12.self_attn.final_linear.weight', 'encoder.transformer.7.self_attn.linear_layers.0.weight', 'encoder.transformer.8.feed_forward.linear_gate.weight', 'encoder.transformer.20.layer_norm_2.weight', 'encoder.transformer.0.layer_norm_2.weight', 'encoder.transformer.2.feed_forward.linear_gate.weight', 'encoder.transformer.5.self_attn.final_linear.weight', 'encoder.transformer.1.feed_forward.linear_1.weight', 'encoder.transformer.31.self_attn.linear_layers.1.weight', 'encoder.transformer.10.self_attn.linear_layers.1.weight', 'encoder.transformer.16.layer_norm_2.weight', 'encoder.transformer.14.feed_forward.linear_2.weight', 'encoder.transformer.30.layer_norm_1.weight', 'encoder.transformer.15.layer_norm_1.weight', 'encoder.transformer.0.self_attn.linear_layers.0.weight', 'encoder.transformer.25.feed_forward.linear_gate.weight', 'encoder.transformer.27.self_attn.linear_layers.0.weight', 'encoder.transformer.24.feed_forward.linear_1.weight', 'encoder.transformer.30.feed_forward.linear_1.weight', 'encoder.transformer.17.self_attn.linear_layers.2.weight', 'encoder.transformer.13.self_attn.linear_layers.0.weight', 'encoder.transformer.25.self_attn.final_linear.weight', 'encoder.transformer.4.feed_forward.linear_2.weight', 'encoder.transformer.14.self_attn.linear_layers.2.weight', 'encoder.transformer.9.self_attn.linear_layers.1.weight', 'encoder.transformer.14.feed_forward.linear_1.weight', 'encoder.transformer.21.layer_norm_2.weight', 'encoder.transformer.11.self_attn.final_linear.weight', 'encoder.transformer.14.layer_norm_2.weight', 'encoder.transformer.17.layer_norm_1.weight', 'encoder.transformer.31.feed_forward.linear_gate.weight', 'encoder.transformer.27.feed_forward.linear_1.weight', 'encoder.transformer.16.feed_forward.linear_2.weight', 'encoder.transformer.23.self_attn.linear_layers.2.weight', 'encoder.transformer.22.self_attn.linear_layers.0.weight', 'encoder.layer_norm.weight']
- This IS expected if you are initializing LlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at ../pretrained_model/llama_7b/7B and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Comment by lantiga** [comment] 2023-04-16 20:02
@rajeevbaalwan the HF conversion script has been revamped with #122, feel free to try again.

Closing this for now, please reopen if you encounter more issues.

**Closed by lantiga** 2023-04-16 20:02 UTC
Labels: enhancement, inference
