### ISSUE TITLE
Error in convert_checkpoint.py when converting 13B weights

### ISSUE THREAD

**Issue by psych0v0yager** [Lightning-AI/lit-llama#110] opened 2023-04-07 06:51 UTC
Whenever I try to convert the 13B weights (unmodified) sourced from the dalai llama download, the first checkpoint successfully completes; however, the second checkpoint fails to convert.

I am using this command:

python scripts/convert_checkpoint.py \
    --output_dir checkpoints/lit-llama \
    --ckpt_dir dalai/llama/models \
    --tokenizer_path /dalai/llama/models/tokenizer.model \
    --model_size 13B

And receive the following error:

python scripts/convert_checkpoint.py     --output_dir checkpoints/lit-llama     --ckpt_dir dalai/llama/models     --tokenizer_path dalai/llama/models/tokenizer.model     --model_size 13B
 50%|███████████████████████████████████████████                                           | 1/2 [00:32<00:32, 32.09s/it]

Killed

**Comment by chrisociepa** [comment] 2023-04-07 08:30
most likely it means you don't have enough RAM

**Comment by psych0v0yager** [comment] 2023-04-07 09:47
I have 32 gb, how much do you need?

**Comment by lantiga** [comment] 2023-04-07 09:49
Work is underway here https://github.com/Lightning-AI/lit-llama/pull/108 to make it cheaper (30GB should suffice)

**Comment by lantiga** [comment] 2023-04-07 10:47
@psych0v0yager I don't think you have enough RAM to hold the 13B model at 32bit precision (you need 48GB).

As a check, try instantiating the 13B model

```
from lit_llama.model import LLaMA

model = LLaMA.from_name("13B")
```

BTW are you loading the original checkpoints? We could provide an option to load incrementally in bfloat16 to reduce the requirements.

**Comment by lantiga** [comment] 2023-04-07 12:00
This should help: https://github.com/Lightning-AI/lit-llama/pull/111

@psych0v0yager can you try this out on your system?

**Comment by psych0v0yager** [comment] 2023-04-08 00:04
Thank you for the prompt replies. 

I attempted the instantiation and additional conversion argument and received the following results.

Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lit_llama.model import LLaMA
>>> 
>>> model = LLaMA.from_name("13B")

Killed

python scripts/convert_checkpoint.py     --output_dir checkpoints/lit-llama     --ckpt_dir /dalai/llama/models     --tokenizer_path /dalai/llama/models/tokenizer.model     --model_size 13B --dtype bfloat16
 50%|█████████████████████████████████████████████████████████████████▌                                                                 | 1/2 [00:46<00:46, 46.04s/it]
Killed

Could it potentially be a VRAM issue? I only have 12 gb in my Nvidia 3060. Furthermore the model weights come from the dalai llama repo (https://github.com/cocktailpeanut/dalai) and I believe they are the full precision weights.

Thanks again for the support

**Comment by chrisociepa** [comment] 2023-04-11 06:54
`Killed` means that the program was killed by your OS. From my experience it appears in 99% when you try using more RAM and SWAP than you have. My advice: run `htop` (or `top`) and check the memory consumption when the script is running to confirm the root cause of the problem. If you dont have enough VRAM, you see OOM exception.

**Comment by lantiga** [comment] 2023-04-16 19:56
Closing this one, feel free to reopen

**Closed by lantiga** 2023-04-16 19:56 UTC
